name: GitHub Metrics
on:
  schedule: [{cron: "0 */8 * * *"}] 
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:

          user: PedroAngeloVargas
          token: ${{ secrets.GITHUB_TOKEN }}
          template: modern 
          base: header, activity, community 
          plugin_traffic: yes 
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: America/Sao_Paulo